### ISSUE TITLE
catch up with upstream

### ISSUE THREAD

**Issue by hansfbaier** [hydrausb3/wch-ch56x-isp#3]
This fork seems to be quite behind the upstream. Getting up to date would be nice

**Comment by bvernoux** [comment]
The aim of that fork is to be as stable as possible for WCH CH569
The aim of this fork is not necessarily to be updated with upstream except if that add something to WCH CH569 (like the configuration of RAMX / ROM size ...)

**Comment by bvernoux** [comment]
I think a refactor of wch-isp could be done in following steps:
* To be detached from original fork from https://github.com/jmaselbas/wch-isp
* To be renamed wch-ch56x-isp 
* Refactor the parameters using https://github.com/likle/cargs (like done in https://github.com/hydrausb3/hydrausb3_host)

**Comment by hansfbaier** [comment]
I would prefer ch56x-isp as a name

**Comment by bvernoux** [comment]
wch-ch56x-isp has been chosen to be coherent with https://github.com/hydrausb3/wch-ch56x-bsp and to avoid confusion with an other chipset which could be called ch56x but not done by WCH

**Comment by hansfbaier** [comment]
ok
